[colors.bright]
black = "#747c84"
blue = "#ae95c7"
cyan = "#95aec7"
green = "#95c7ae"
magenta = "#c795ae"
red = "#c7ae95"
white = "#f3f4f5"
yellow = "#aec795"

[colors.cursor]
cursor = "#c7ccd1"
text = "#1c2023"

[colors.normal]
black = "#1c2023"
blue = "#ae95c7"
cyan = "#95aec7"
green = "#95c7ae"
magenta = "#c795ae"
red = "#c7ae95"
white = "#c7ccd1"
yellow = "#aec795"

[colors.primary]
background = "#1c2023"
foreground = "#c7ccd1"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/bin/fish"
